/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-generated-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_Meter = map[string]string{
	"": "Meter",
}

func (Meter) SwaggerDoc() map[string]string {
	return map_Meter
}

var map_MeterList = map[string]string{
	"": "MeterList contains a list of Meter",
}

func (MeterList) SwaggerDoc() map[string]string {
	return map_MeterList
}

var map_MeterSpec = map[string]string{
	"workspace": "workspace ref",
	"category":  "repository category: api/mock/web/app/jmeter",
}

func (MeterSpec) SwaggerDoc() map[string]string {
	return map_MeterSpec
}

// AUTO-GENERATED FUNCTIONS END HERE
